name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

jobs:
  rust-ci:
    uses: qubit-ltd/rs-ci/.github/workflows/rust-ci.yml@89562a86c0d9419595895b6dc45c8210ca70f59f
    with:
      cargo_fuzz_max_len: "16384"
      coverage_enforce_thresholds: "1"
    secrets: inherit
